### ISSUE TITLE
X-Request-ID is not an integer

### ISSUE THREAD

**Issue by eXeDK** [CurrencyCloud/currencycloud-swagger#38]
We used the swagger file in this repo to generate a Go client. Sadly we are running into some issues when using the generated client. It seems like this swagger is not up to date to the one deployed. 

Specifically we are are receiving `X-Request-ID`'s that are not integers as they are defined in the swagger spec. Instead we are receiving UUID's. 

Can you please update the swagger spec to the currently deployed so we can generate a new Go client?

**Comment by EAddario** [comment]
Confirmed as a bug. We'll merge #39 once we finish tests

**Comment by EAddario** [comment]
PR merged into master. Many thanks @eXeDK
